### ISSUE TITLE
Duplicate repository?

### ISSUE THREAD

**Issue by pbek** [norbusan/qownnotes-debian#1]
Hi Norbert,

thank you for your care about QOwnNotes! But is there anything major wrong with my Debian respositories at https://build.opensuse.org/package/show/home:pbek:QOwnNotes/desktop? :grin: 

See: https://www.qownnotes.org/installation#Debian

**Comment by norbusan** [comment]
Hi @pbek 
I have answered on my blog (saw this here only afterwards). I repeat it here, so that we can continue the discussion here, which is easier.

---- from the blog ----
first of all thanks for your great program and all the work you are putting into it!!!!
Concerning the build, there are a few reasons for me: One is that as far as I can see, the repository you provide is for Ubuntu, and thus there might be a version twist (in particular starting from this month when the import freeze from Debian to Ubuntu happens). It is also not so straight-forward to use a PPA on Debian, at least afair.
I see now that the build service on OpenSUSE also has builds for Debian/buster, but the one for unstable (testing) failed.
Furthermore, I switched the build system to a much simpler code (just dh 12 qmake build system).

But yes, strictly speaking it is not necessary, but I found it more convenient for me to do it myself.

**Comment by pbek** [comment]
> first of all thanks for your great program and all the work you are putting into it!!!!

thank you :smile: 

> but the one for unstable (testing) failed.

It just failed yesterday (for 20.2.9), QON 20.2.8 is still available. I'm sure the SuSE guys (and girls) are fixing OBS for Debian Testing soon.

> But yes, strictly speaking it is not necessary, but I found it more convenient for me to do it myself.

No worries then. :grin:

**Comment by norbusan** [comment]
Hi @pbek 
Thanks for your understanding! BTW, what is your opinion concerning upload to Debian? You are shipping out new versions on a nearly daily basis (impressive) - do you prefer the ppa for Ubuntu, or having a package in Debian (which would be pulled into the next Ubuntu release)?

Norbert

PS: Und liebe Grüße in das schöne Graz (von einem Auslandsösterreicher)

**Comment by pbek** [comment]
> do you prefer the ppa for Ubuntu, or having a package in Debian

There is a PPA for Ubuntu and the OBS Debian repositories for Debian. Or are you talking about an actual package in the Debian repository? I wouldn't mind that, since people would still be able to get the latest versions from the external repositories...

And in Ubuntu also the snap versions is available as latest version in the stores.

(btw. https://build.opensuse.org/package/binaries/home:pbek:QOwnNotes/desktop/Debian_Unstable is building again)

> PS: Und liebe Grüße in das schöne Graz (von einem Auslandsösterreicher)

Dankeschön, ich habe schon gesehen dass du offenbar ausgewandert bist. :grin: Wie hat es dich nach Japan verschlagen? :japanese_castle:
